print("Airtime purchase")
print(" a.mtn\n b.airtel\n c.9mobile\n d.Glo\n")
response = str(input(" ")).lower()
mobile_number = input("please enter your phone number:")
airtime_cost = int(input("please enter the amount of airtime you want to purchase:"))
print("you have succesfully purchase your #{airtime_cost} for airtime of {mobile_number}:")
# data purchase
print("Data purchase")
print(" a.mtn\n b.airtel\n c.9mobile\n d.Glo\n")
Data = input("please input mobile number:")
Data_cost = int(input("please enter the amount of data you want to purchase {amount of Data}"))
print("you have successfully purchase {data_cost} for {mobile number}:")
